"""Render the canonical glossary into an app-consumable JSON artifact.

site/data/glossary.yml is the single source of truth. The app must not parse
YAML at runtime (no PyYAML in the deployed requirements), so this build step
emits a flat term -> definition map into app/assets/glossary.json.
"""

from __future__ import annotations

import json
from pathlib import Path

import yaml

APP_DIR = Path(__file__).resolve().parents[1]
PROJECT_DIR = APP_DIR.parent

GLOSSARY_YML = PROJECT_DIR / "site" / "data" / "glossary.yml"
GLOSSARY_JSON = APP_DIR / "assets" / "glossary.json"
GLOSSARY_INCLUDE = PROJECT_DIR / "site" / "_includes" / "glossary_body.md"


def _static_markdown(terms: list[dict]) -> str:
    groups: dict[str, list[dict]] = {}
    for entry in terms:
        groups.setdefault(entry.get("group", "General"), []).append(entry)
    blocks = ["<!-- Generated by app/scripts/26_build_glossary.py from data/glossary.yml. Do not edit. -->"]
    for group in sorted(groups):
        blocks.append(f'\n::: {{.glossary-group}}\n### {group}\n\n<dl class="glossary">')
        for entry in sorted(groups[group], key=lambda e: e["term"].lower()):
            definition = " ".join(entry["definition"].split())
            blocks.append(f"<dt>{entry['term']}</dt><dd>{definition}</dd>")
        blocks.append("</dl>\n:::")
    return "\n".join(blocks) + "\n"


def main() -> None:
    terms = yaml.safe_load(GLOSSARY_YML.read_text(encoding="utf-8"))["terms"]

    flat = {entry["term"]: " ".join(entry["definition"].split()) for entry in terms}
    GLOSSARY_JSON.parent.mkdir(parents=True, exist_ok=True)
    GLOSSARY_JSON.write_text(json.dumps(flat, indent=2, sort_keys=True), encoding="utf-8")

    # Static include so the site renders with zero code execution (no CI Python).
    GLOSSARY_INCLUDE.parent.mkdir(parents=True, exist_ok=True)
    GLOSSARY_INCLUDE.write_text(_static_markdown(terms), encoding="utf-8")

    print(json.dumps({"status": "glossary", "terms": len(flat)}, indent=2))


if __name__ == "__main__":
    main()
